#!/usr/bin/env bash

###########################
# xbindkeys configuration #
###########################
#
# Version: 0.1.3
#
# If you edit this, do not forget to uncomment any lines that you change.
# The pound(#) symbol may be used anywhere for comments.
#
# A list of keys is in /usr/include/X11/keysym.h and in
# /usr/include/X11/keysymdef.h
# The XK_ is not needed.
#
# List of modifier (on my keyboard):
#   Control, Shift, Mod1 (Alt), Mod2 (NumLock),
#   Mod3 (CapsLock), Mod4, Mod5 (Scroll).
#
# Another way to specifie a key is to use 'xev' and set the
# keycode with c:nnn or the modifier with m:nnn where nnn is
# the keycode or the state returned by xev
#
# This file is created by xbindkey_config
# The structure is :
# # Remark
# "command"
# m:xxx + c:xxx
# Shift+...




#keystate_numlock = enable
#keystate_scrolllock = enable
#keystate_capslock = enable



# Toggle Firefox
"jumpapp -m firefox"
  control+alt+c

# Toggle VS Code
# "jumpapp -f -m code-insiders"
"wmctrl -x -a 'Code - Insiders'"
  control+alt+e

# Toggle Sublime Text
"jumpapp -m subl3"
  control+alt+w

# Toggle Telegram
"jumpapp -m telegram-desktop"
  control+alt+q

# Toggle Dolphin
"jumpapp -m dolphin"
  control+alt+f

# Toggle Settings
"jumpapp -m systemsettings5"
  control+shift+comma

# Toggle Pamac Manager
"jumpapp -m pamac-manager"
  control+alt+p

# Toggle Konsole
"jumpapp -m konsole"
  control+alt+1

# Toggle Tilix
"jumpapp -m tilix --maximize"
  control+alt+2

# mouse button 8 sends Control + PageDown
# "xdotool key 'Alt_L+Left'"
#   b:8

# # mouse button 8 sends Control + PageDown
# "amixer set Master 5%+"
#   alt+F12

# "amixer set Master 5%-"
#   alt+F11




# mouse button 9 sends Control + PageUp
# "xvkbd -xsendevent -text '\A\[Right]'"
#   b:9

# mouse button 8 sends Control + PageDown
# "xvkbd -xsendevent -text '\A\[Left]'"
#   b:8

#
# End of xbindkeys configuration
