#!/usr/bin/env bash
# vim: ft=sh

# ~/.xprofile - X11-specific login script (after ~/.profile)

[ -f "$HOME/.profile" ] && . "$HOME/.profile"



# export GTK_CSD=0
export LD_PRELOAD="/usr/lib/libgtk3-nocsd.so.0"
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_LOGGING_RULES=’*.debug=false’

# xbindkeys

# if [ ! "$DESKTOP_SESSION" ]; then

# fi

# swap Capslock with Backspace
# setxkbmap -option caps:backspace
# setxkbmap -option shift:both_capslock
