#!/usr/bin/env bash
# vim: ft=sh

# ~/.xprofile - X11-specific login script (after ~/.profile)

xbindkeys

# if [ ! "$DESKTOP_SESSION" ]; then

# fi

# swap Capslock with Backspace
# setxkbmap -option caps:backspace
# setxkbmap -option shift:both_capslock

