# vim:syntax=zsh
# vim:filetype=zsh

if [[ "$SYSTEM" = "Darwin"  ]]; then
  # system executables
  #export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/libexec
  # local system binaries
  export PATH="/usr/local/sbin:/usr/local/bin:$PATH"
elif [[ "$SYSTEM" = "Linux"  ]]; then
  if [ -d "/home/linuxbrew/.linuxbrew" ]; then
    eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
    export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
  fi
fi

# https://github.com/sindresorhus/pure#options
export PURE_PROMPT_SYMBOL='❯'

# https://github.com/rupa/z
export _Z_DATA="$XDG_CACHE_HOME/zsh/z"

#
# Executes commands at login before zshrc.
#
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
  export LANGUAGE=en_US.UTF-8
fi

export LC_COLLATE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LESSCHARSET=utf-8

# eliminates duplicates in *paths
typeset -gU cdpath fpath path

# Zsh search path for executable
path=(
  /usr/local/{bin,sbin}
  $path
)
