#!/usr/bin/env zsh
# vim:syntax=zsh
# vim:filetype=zsh

# for profiling zsh
# https://unix.stackexchange.com/a/329719/27109
#
#zmodload zsh/zprof

# ─── Customizing Paths ────────────────────────────────────────────────────────
export ZSHCONFIG="${ZDOTDIR:-$XDG_CONFIG_HOME}/zsh"

# initial Zplugin's hash definition, if configuring before loading Zplugin
declare -A ZPLGM
ZPLG_HOME="$XDG_CACHE_HOME/zsh/zplugin"
ZPLGM[HOME_DIR]="$ZPLG_HOME"
ZPLGM[ZCOMPDUMP_PATH]="$XDG_CACHE_HOME/zsh/zcompdump"

# ─── Install zplugin if not installed ─────────────────────────────────────────

if [[ ! -d "$ZPLG_HOME" ]]; then
	git clone https://github.com/psprint/zplugin "$ZPLG_HOME/bin"
	# zcompile $ZPLG_HOME/bin/zplugin.zsh
fi

# if [ ! -d "${ZPLG_HOME}" ]; then
#   sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"
# fi

source "$ZPLG_HOME/bin/zplugin.zsh"
autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin

# and load the plugins
source "$ZSHCONFIG/zplugin-init.zsh"
# ──────────────────────────────────────────────────────────────────────────────


#
# ─── SETTING AUTOLOADED FUNCTIONS ────────────────────────────────────────────
#
zsh_fpath="${ZSHCONFIG}/autoloaded"
fpath=($zsh_fpath $fpath)
if [[ -d "$zsh_fpath" ]]; then
  for func in $zsh_fpath/*; do
    autoload -Uz ${func:t}
  done
fi
unset zsh_fpath

#
# ─── LOAD ALL SCRIPTS ${ZSHCONFIG}/lib/*.zsh───────────────────────────────────
#
zsh_lib=${ZSHCONFIG}/lib
if [[ -d "$zsh_lib" ]]; then
  for file in $zsh_lib/*.zsh; do
    source $file
  done
fi
unset zsh_lib

# ──────────────────────────────────────────────────────────────────────────────


#
# https://gist.github.com/ctechols/ca1035271ad134841284
# https://carlosbecker.com/posts/speeding-up-zsh
# https://gist.github.com/ctechols/ca1035271ad134841284#gistcomment-2894219
#
# autoload -Uz compinit

case $SYSTEM in
  Darwin)
    if [ $(date +'%j') != $(/usr/bin/stat -f '%Sm' -t '%j' ${ZDOTDIR:-$HOME}/.zcompdump) ]; then
      compinit;
    else
      compinit -C;
    fi
    ;;
  Linux)
    # not yet match GNU & BSD stat
  ;;
esac

# see zplugin-init.zsh with Turbo Mode
#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# https://direnv.net/ 
# see zplugin-init.zsh
# https://github.com/zdharma/zplugin/wiki/Direnv-explanation
#eval "$(direnv hook zsh)"


# Private script here
# [ -f ~/.private.zsh ] && source ~/.private.zsh
