actions:
  rebuildcache: |
    echo "        -> Rebuild the KService desktop file system configuration cache"
    /usr/bin/kbuildsycoca5
  gtkfilechooser: gsettings set org.gtk.Settings.FileChooser startup-mode cwd
  czdeps: yarn global add commitizen @metahub/cz-conventional-commit
  fontcache: fc-cache -rv
  install_fonts: sudo ./dotfiles/config/fontconfig/fonts/install.sh
  install_vimplug: |
    test -e ~/.vim/autoload/plug.vim || (
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    nvim +PlugInstall +qall )
  exec_yay: yay -S --needed --noconfirm --useask {0}
  exec_pipenv: pipenv install --dev && pipenv run {0}
  pre:
    install_pkgs: yay -S --needed --noconfirm --useask $(grep -v '^\s*$\|^\s*\#' packages.txt)
  post:
    loginstall: echo {{@@ _dotfile_abs_src @@}} installed to {{@@ _dotfile_abs_dst
      @@}} >> {0}
    make_pkg: pushd /tmp && yay -G {0} && cd {0} && makepkg -sci --noconfirm --skippgpcheck
      && popd
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
  minversion: 0.29.4
dotfiles:
  d_bin:
    src: bin
    dst: ~/.bin
  f_profile:
    src: bash/profile
    dst: ~/.profile
  f_inputrc:
    src: bash/inputrc
    dst: ~/.inputrc
  f_bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  f_bash_prompt:
    src: bash/bash_prompt
    dst: ~/.bash_prompt
  f_bash_profile:
    src: bash/bash_profile
    dst: ~/.bash_profile
  f_bash_completion:
    src: bash/bash_completion
    dst: ~/.bash_completion
  f_bash_logout:
    src: bash/bash_logout
    dst: ~/.bash_logout
  d_completions:
    src: bash/completions
    dst: ~/.bash/completions
  f_aliases:
    src: aliases
    dst: ~/.aliases
  f_exports:
    src: exports
    dst: ~/.exports
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zprofile:
    src: zsh/zprofile
    dst: ~/.config/zsh/.zprofile
  f_zshrc:
    src: zsh/zshrc
    dst: ~/.config/zsh/.zshrc
  f_zlogin:
    src: zsh/zlogin
    dst: ~/.config/zsh/.zlogin
  f_zinit:
    src: zsh/zinit.zsh
    dst: ~/.config/zsh/zinit.zsh
  f_zconfig:
    src: zsh/config
    dst: ~/.config/zsh/config
  d_fsh:
    src: config/fsh
    dst: ~/.config/fsh
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_git:
    src: config/git
    dst: ~/.config/git
  f_dir_colors:
    src: dir_colors
    dst: ~/.dir_colors
  f_npmrc:
    src: npmrc
    dst: ~/.npmrc
  f_curlrc:
    src: curlrc
    dst: ~/.curlrc
  f_gemrc:
    src: gemrc
    dst: ~/.gemrc
  f_wgetrc:
    src: wgetrc
    dst: ~/.wgetrc
  f_exrc:
    src: exrc
    dst: ~/.exrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_less:
    src: config/less
    dst: ~/.config/less
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_micro:
    src: config/micro
    dst: ~/.config/micro
    link: link_children
  d_ripgrep:
    src: config/ripgrep
    dst: ~/.config/ripgrep
  d_htop:
    src: config/htop
    dst: ~/.config/htop
  f_yarnrc:
    src: yarnrc
    dst: ~/.yarnrc
  d_asciinema:
    src: config/asciinema
    dst: ~/.config/asciinema
  f_tldrrc:
    src: tldrrc
    dst: ~/.tldrrc
  f_youtubedl:
    src: config/youtube-dl/config
    dst: ~/.config/youtube-dl/config
  f_mpd:
    src: config/mpd/mpd.conf
    dst: ~/.config/mpd/mpd.conf
  d_gnupg:
    src: gnupg
    dst: ~/.gnupg
    link: link_children
  f_colorls:
    src: config/colorls/dark_colors.yaml
    dst: ~/.config/colorls/dark_colors.yaml
  d_svgo:
    src: config/svgo
    dst: ~/.config/svgo
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_katerc:
    src: config/katerc
    dst: ~/.config/katerc
  f_katemoderc:
    src: config/katemoderc
    dst: ~/.config/katemoderc
  f_kateschemarc:
    src: config/kateschemarc
    dst: ~/.config/kateschemarc
  f_katesyntaxhighlightingrc:
    src: config/katesyntaxhighlightingrc
    dst: ~/.config/katesyntaxhighlightingrc
  f_kateuirc:
    src: local/share/kxmlgui5/kate/kateui.rc
    dst: ~/.local/share/kxmlgui5/kate/kateui.rc
  f_chromium-flags:
    src: config/chromium-flags.conf
    dst: ~/.config/chromium-flags.conf
  f_chromium_preferences:
    src: config/chromium/Default/Preferences
    dst: ~/.config/chromium/Default/Preferences
  f_dolphin_servicemenus:
    src: local/share/kservices5/ServiceMenus
    dst: ~/.local/share/kservices5/ServiceMenus
    link: nolink
  f_gtk2rc:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  f_gtk2:
    src: config/gtk-2.0/gtkfilechooser.ini
    dst: ~/.config/gtk-2.0/gtkfilechooser.ini
  d_gtk3:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  f_xsession:
    src: xsession
    dst: ~/.xsession
profiles:
  all:
    dotfiles:
    - ALL
  base:
    dotfiles:
    - f_exrc
    - f_vimrc
    - d_micro
    - d_htop
    - f_npmrc
    - f_yarnrc
    - f_curlrc
    - f_gemrc
    - f_wgetrc
    - f_less
    - d_ripgrep
    - d_asciinema
    include:
    - shell
    - git
  git:
    dotfiles:
    - f_gitconfig
    - d_git
  bash:
    dotfiles:
    - f_profile
    - f_inputrc
    - f_bashrc
    - f_bash_prompt
    - f_bash_profile
    - f_bash_completion
    - f_bash_logout
    - d_completions
  zsh:
    dotfiles:
    - f_zshenv
    - f_zprofile
    - f_zshrc
    - f_zlogin
    - f_zinit
    - f_zconfig
  shell:
    dotfiles:
    - d_bin
    - d_fsh
    - f_aliases
    - f_exports
    - f_dir_colors
    - d_bat
    include:
    - bash
    - zsh
  other:
    dotfiles:
    - f_tldrrc
    - f_youtubedl
    - f_mpd
    - d_gnupg
    - f_colorls
    - d_svgo
  kde:
    dotfiles:
    - f_xmodmap
  kde-kate:
    dotfiles:
    - f_katerc
    - f_katemoderc
    - f_kateschemarc
    - f_katesyntaxhighlightingrc
    - f_kateuirc
  chromium:
    dotfiles:
    - f_chromium-flags
    - f_chromium_preferences
  dolphin:
    dotfiles:
    - f_dolphin_servicemenus
    actions:
    - rebuildcache
  gtk:
    dotfiles:
    - f_gtk2rc
    - f_gtk2
    - d_gtk3
    - f_xsession
    actions:
    - gtkfilechooser
  art:
    dotfiles:
dynvariables:
  home: echo $HOME
  os: echo $OSTYPE
