config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
  import_variables:
  - tasks/variables/dynvariables.yaml
  import_actions:
  - tasks/actions/base.yaml
  # import_configs:
  # - configs/all.yaml
  minversion: 0.32.0
dotfiles:
  d_bin:
    src: bin
    dst: ~/.local/bin
    link: link_children
  f_profile:
    src: profile
    dst: ~/.profile
  f_inputrc:
    src: bash/inputrc
    dst: ~/.config/inputrc
  f_bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  f_bash_prompt:
    src: bash/bash_prompt
    dst: ~/.bash_prompt
  f_bash_profile:
    src: bash/bash_profile
    dst: ~/.bash_profile
  f_bash_completion:
    src: bash/bash_completion
    dst: ~/.bash_completion
  f_bash_logout:
    src: bash/bash_logout
    dst: ~/.bash_logout
  d_completions:
    src: bash/completions
    dst: ~/.bash/completions
  f_aliases:
    src: aliases
    dst: ~/.aliases
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zprofile:
    src: zsh/zprofile
    dst: ~/.config/zsh/.zprofile
  f_zshrc:
    src: zsh/zshrc
    dst: ~/.config/zsh/.zshrc
  f_zlogin:
    src: zsh/zlogin
    dst: ~/.config/zsh/.zlogin
  f_zinit:
    src: zsh/zinit.zsh
    dst: ~/.config/zsh/zinit.zsh
  d_zconfig:
    src: zsh/config
    dst: ~/.config/zsh/config
  d_zshenv:
    src: zsh/zshenv.d
    dst: ~/.config/zsh/zshenv.d
  d_fsh:
    src: config/fsh
    dst: ~/.config/fsh
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_git:
    src: config/git
    dst: ~/.config/git
  f_dir_colors:
    src: dir_colors
    dst: ~/.dir_colors
  f_curlrc:
    src: curlrc
    dst: ~/.curlrc
  d_gemrc:
    src: config/gem
    dst: ~/.config/gem
  d_wget:
    src: config/wget
    dst: ~/.config/wget
  f_exrc:
    src: exrc
    dst: ~/.exrc
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_less:
    src: config/less
    dst: ~/.config/less
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_micro:
    src: config/micro
    dst: ~/.config/micro
    link: link_children
  d_nano:
    src: config/nano
    dst: ~/.config/nano
  d_ripgrep:
    src: config/ripgrep
    dst: ~/.config/ripgrep
  d_htop:
    src: config/htop
    dst: ~/.config/htop
  f_npmrc:
    src: config/npm/npmrc
    dst: ~/.config/npm/npmrc
  f_yarnrc:
    src: yarnrc
    dst: ~/.yarnrc
  d_asciinema:
    src: config/asciinema
    dst: ~/.config/asciinema
  f_tldrrc:
    src: tldrrc
    dst: ~/.tldrrc
  f_youtubedl:
    src: config/youtube-dl/config
    dst: ~/.config/youtube-dl/config
  f_mpd:
    src: config/mpd/mpd.conf
    dst: ~/.config/mpd/mpd.conf
  d_gnupg:
    src: config/gnupg
    dst: ~/.config/gnupg
    link: link_children
  d_colorls:
    src: config/colorls
    dst: ~/.config/colorls
  d_svgo:
    src: config/svgo
    dst: ~/.config/svgo
  f_katerc:
    src: config/katerc
    dst: ~/.config/katerc
  f_katemoderc:
    src: config/katemoderc
    dst: ~/.config/katemoderc
  f_kateschemarc:
    src: config/kateschemarc
    dst: ~/.config/kateschemarc
  f_katesyntaxhighlightingrc:
    src: config/katesyntaxhighlightingrc
    dst: ~/.config/katesyntaxhighlightingrc
  f_kateuirc:
    src: local/share/kxmlgui5/kate/kateui.rc
    dst: ~/.local/share/kxmlgui5/kate/kateui.rc
  f_konsolerc:
    src: config/konsolerc
    dst: ~/.config/konsolerc
  f_konsole_bash-profile:
    src: local/share/konsole/bash.profile
    dst: ~/.local/share/konsole/bash.profile
  f_konsole_zsh-profile:
    src: local/share/konsole/zsh.profile
    dst: ~/.local/share/konsole/zsh.profile
  f_konsole_base16-default-dark-256:
    src: local/share/konsole/base16-default-dark-256.colorscheme
    dst: ~/.local/share/konsole/base16-default-dark-256.colorscheme
  f_konsole_base16-default-dark:
    src: local/share/konsole/base16-default-dark.colorscheme
    dst: ~/.local/share/konsole/base16-default-dark.colorscheme
  f_konsole_base16-tomorrow-night-256:
    src: local/share/konsole/base16-tomorrow-night-256.colorscheme
    dst: ~/.local/share/konsole/base16-tomorrow-night-256.colorscheme
  f_konsole_base16-tomorrow-night:
    src: local/share/konsole/base16-tomorrow-night.colorscheme
    dst: ~/.local/share/konsole/base16-tomorrow-night.colorscheme
  f_chromium-flags:
    src: config/chromium-flags.conf
    dst: ~/.config/chromium-flags.conf
  f_chromium_preferences:
    src: config/chromium/Default/Preferences
    dst: ~/.config/chromium/Default/Preferences
  f_dolphin_servicemenus:
    src: local/share/kservices5/ServiceMenus
    dst: ~/.local/share/kservices5/ServiceMenus
    link: nolink
  f_gtkrc2:
    src: config/gtk-2.0/gtkrc-2.0
    dst: ~/.gtkrc-2.0
    link: nolink
  f_gtk2:
    src: config/gtk-2.0/gtkfilechooser.ini
    dst: ~/.config/gtk-2.0/gtkfilechooser.ini
  d_gtk3:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
    link: nolink
  f_xbindkeysrc:
    src: xbindkeysrc
    dst: ~/.xbindkeysrc
  f_xinitrc:
    src: config/X11/xinitrc
    dst: ~/.config/X11/xinitrc
  f_xsession:
    src: xsession
    dst: ~/.xsession
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  f_xresourcese:
    src: config/Xresources
    dst: ~/.config/Xresources
  d_firefox:
    src: firefox
    dst: '{{@@ mozpath @@}}'
    link: link_children
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  f_package-control:
    src: config/sublime-text-3
    dst: ~/.config/sublime-text-3
    link: link_children
  f_fontsconfig:
    src: config/fontconfig/fonts.conf
    dst: ~/.config/fontconfig/fonts.conf
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
profiles:
  all:
    dotfiles:
    - ALL
  bin:
    dotfiles:
    - d_bin
  node:
    dotfiles:
    - f_npmrc
    - f_yarnrc
    - d_gemrc
  base:
    dotfiles:
    - d_htop
    - f_curlrc
    - d_wget
    - f_less
    - d_ripgrep
    - d_neofetch
    include:
    - shell
    - git
  editors:
    dotfiles:
    - f_exrc
    - f_vimrc
    - d_nano
    - d_micro
  git:
    dotfiles:
    - f_gitconfig
    - d_git
  bash:
    dotfiles:
    - f_profile
    - f_inputrc
    - f_bashrc
    - f_bash_prompt
    - f_bash_profile
    - f_bash_completion
    - f_bash_logout
    - d_completions
  zsh:
    dotfiles:
    - f_zshenv
    - f_zprofile
    - f_zshrc
    - f_zlogin
    - f_zinit
    - d_zconfig
    - d_zshenv
  shell:
    dotfiles:
    - d_bin
    - d_fsh
    - f_aliases
    - f_dir_colors
    - d_bat
    include:
    - bash
    - zsh
  fonts:
    dotfiles:
    - f_fontsconfig
  other:
    dotfiles:
    - f_tldrrc
    - f_youtubedl
    - f_mpd
    - d_gnupg
    - d_colorls
    - d_svgo
  kde:
    dotfiles:
    - f_xinitrc
    - f_xbindkeysrc
    - f_xmodmap
    - f_xprofile
    - f_xresourcese
  kde-kate:
    dotfiles:
    - f_katerc
    - f_katemoderc
    - f_kateschemarc
    - f_katesyntaxhighlightingrc
    - f_kateuirc
  kde-konsole:
    dotfiles:
    - f_konsolerc
    - f_konsole_bash-profile
    - f_konsole_zsh-profile
    - f_konsole_base16-default-dark-256
    - f_konsole_base16-default-dark
    - f_konsole_base16-tomorrow-night-256
    - f_konsole_base16-tomorrow-night
  kde-dolphin:
    dotfiles:
    - f_dolphin_servicemenus
    actions:
    - rebuildcache
  chromium:
    dotfiles:
    - f_chromium-flags
    - f_chromium_preferences
  gtk:
    dotfiles:
    - f_gtkrc2
    - f_gtk2
    - d_gtk3
    - f_xsession
    actions:
    - gtkfilechooser
  firefox:
    dotfiles:
    - d_firefox
  # sublime:
  #   dotfiles:
  #   - f_package-control
  #   actions:
  #   - install-package-control

  art:
    dotfiles:
    - d_sxhkd
