config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
  minversion: 0.29.4
dotfiles:
  d_bin:
    src: bin
    dst: ~/.bin
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  f_zprofile:
    src: zsh/zprofile
    dst: ~/.config/zsh/.zprofile
  f_zshrc:
    src: zsh/zshrc
    dst: ~/.config/zsh/.zshrc
  f_zlogin:
    src: zsh/zlogin
    dst: ~/.config/zsh/.zlogin
  f_zplugin:
    src: zsh/zplugin.zsh
    dst: ~/.config/zsh/zplugin.zsh
  f_zconfig:
    src: zsh/config
    dst: ~/.config/zsh/config
  d_config_fsh:
    src: config/fsh
    dst: ~/.config/fsh
  f_profile:
    src: bash/profile
    dst: ~/.profile
  f_inputrc:
    src: bash/inputrc
    dst: ~/.inputrc
  f_bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  f_bash_prompt:
    src: bash/bash_prompt
    dst: ~/.bash_prompt
  f_bash_profile:
    src: bash/bash_profile
    dst: ~/.bash_profile
  f_bash_completion:
    src: bash/bash_completion
    dst: ~/.bash_completion
  f_bash_logout:
    src: bash/bash_logout
    dst: ~/.bash_logout
  d_completions:
    src: bash/completions
    dst: ~/.bash/completions
  f_aliases:
    src: aliases
    dst: ~/.aliases
  f_exports:
    src: exports
    dst: ~/.exports
  f_less:
    src: config/less
    dst: ~/.config/less
  d_gnupg:
    src: gnupg
    dst: ~/.gnupg
    link: link_children
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_config:
    src: config/youtube-dl/config
    dst: ~/.config/youtube-dl/config
  f_dir_colors:
    src: dir_colors
    dst: ~/.dir_colors
  f_dark_colors.yaml:
    src: config/colorls/dark_colors.yaml
    dst: ~/.config/colorls/dark_colors.yaml
  f_mpd.conf:
    src: config/mpd/mpd.conf
    dst: ~/.config/mpd/mpd.conf
profiles:
  base:
    dotfiles:
    - ALL
