#!/usr/bin/env zsh

# vim:syntax=zsh
# vim:filetype=zsh

# for profiling zsh
# https://unix.stackexchange.com/a/329719/27109
#
# zmodload zsh/zprof
# typeset -g ZINIT_MOD_DEBUG=1

# ─── Customizing Paths ────────────────────────────────────────────────────────
export ZSHCONFIG="${ZDOTDIR:-$XDG_CONFIG_HOME/zsh}"

# initial zinit's hash definition, if configuring before loading zinit
declare -A ZINIT
ZINIT_HOME="$XDG_CACHE_HOME/zsh/zinit"
ZINIT[HOME_DIR]="$ZINIT_HOME"
ZINIT[ZCOMPDUMP_PATH]="$XDG_CACHE_HOME/zsh/zcompdump"

# ─── Install zinit if not installed ─────────────────────────────────────────

if [[ ! -d "$ZINIT_HOME" ]]; then
	git clone https://github.com/zdharma/zinit "$ZINIT_HOME/bin"
  # sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
fi

source "$ZINIT_HOME/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# and load the plugins
# source "$ZSHCONFIG/zinit-init.zsh"
source "$ZSHCONFIG/zinit.zsh"
# ──────────────────────────────────────────────────────────────────────────────

#
# ─── LOAD ALL SCRIPTS ${ZSHCONFIG}/config/*.zsh ───────────────────────────────
#

zsh_config="${ZSHCONFIG}/config"
if [[ -d "$zsh_config" ]]; then
  for file in $zsh_config/*.zsh; do
    source "$file"
  done
fi
unset zsh_config

#
# ─── SETTING AUTOLOADED FUNCTIONS ────────────────────────────────────────────
#
zsh_fpath="$HOME/.bin"
fpath=($zsh_fpath $fpath)
if [[ -d "$zsh_fpath" ]]; then
  for func in $zsh_fpath/*; do
    autoload -Uz ${func:t}
  done
fi
unset zsh_fpath

# https://direnv.net/
# see zinit-init.zsh
# https://github.com/zdharma/zinit/wiki/Direnv-explanation
#eval "$(direnv hook zsh)"

# Private script here
# [ -f ~/.private.zsh ] && source ~/.private.zsh
