actions:
  rebuildcache: |
    echo "        -> Rebuild the KService desktop file system configuration cache"
    /usr/bin/kbuildsycoca5
  gtkfilechooser: gsettings set org.gtk.Settings.FileChooser startup-mode cwd
  install-package-control: |
    echo "        -> Installing Sublime Text Package Control"
    mkdir -p "$HOME/.config/sublime-text-3/Installed Packages"
    curl https://packagecontrol.io/Package%20Control.sublime-package -o $HOME/.config/sublime-text-3/Installed\ Packages/Package\ Control.sublime-package
